name: FTP Deploy

on:
  workflow_dispatch:  # 手動実行も可能
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"                # ローカルのディレクトリを指定
          server-dir: "/ikoiko/"            # サーバー上のデプロイ先ディレクトリ
          protocol: "ftp"                # プロトコルをFTPに設定
          state-name: .ftp-deploy-sync-state.json  # 同期状態を保存
          dry-run: false                  # 実際にデプロイ
          log-level: verbose              # 詳細ログ
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            .claude/**
            CLAUDE.md
            README.md
            *.log
            .DS_Store
            .ftp-deploy-sync-state.json
